Intake commands
ETechChargers5298/ChargedUp2023 pull request #36
Opened 2023-01-28 16:31 UTC by ElijahLigon2023

intake commands :DDDDD

2023-01-28 16:42 UTC, Tqkoyaki requested changes
IntakeChomp is good. Mimic that for IntakeEat in line 14 you are missing code and IntakeSpit you need to change the code on line 13.

2023-01-28 19:52 UTC, botkii approved these changes
ya fixed it :D

2023-01-28 19:53 UTC, botkii approved these changes
a

2023-02-01 15:03 UTC, botkii approved these changes

2023-02-01 15:03 UTC, merged